base: &base
  adapter: mysql2
  username: root
  password: zdk
  host: localhost
  encoding: utf8
  reconnect: true
  wait_timeout: 600

development:
  <<: *base
  database: herb

production:
  <<: *base
  database: herb
